<?php
/**
 * Created by PhpStorm.
 * User: dsmrt
 * Date: 1/12/18
 * Time: 9:33 PM
 */

namespace flipbox\keychain\records;

use flipbox\keychain\KeyChain;

/**
 * Class KeyChainRecord
 * @package flipbox\keychain\records
 * @property int $id
 * @property string $certificate
 * @property string $key
 * @property bool $enabled
 * @property bool $isEncrypted
 * @property string $pluginHandle
 */
class KeyChainRecord extends \craft\db\ActiveRecord
{
    use EmberTrait;

    public $decryptedKey;
    public $decryptedCertificate;

    /**
     * @var bool
     * This is how we know if the key and cert has been decrypted
     */
    public $isDecrypted = false;

    /**
     * The table alias
     */
    const TABLE_ALIAS = 'keychain';


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return array_merge(
            [
                [['key', 'certificate'], 'required'],
                ['certificate', 'isCertificateX509'],
                ['key', 'isKeyCertAPair']
            ],
            parent::rules()
        );
    }

    /**
     * @param $attribute
     * @param $params
     * @param $validator
     */
    public function isCertificateX509($attribute, $params, $validator)
    {
        $cert = $this->getDecryptedCertificateObject();
        if (!$cert) {
            $this->addError($attribute, 'Certificate is not a x509 certificate');
        }
    }

    /**
     * @param $attribute
     * @param $params
     * @param $validator
     */
    public function isKeyCertAPair($attribute, $params, $validator)
    {
        $key = openssl_pkey_get_private($this->getDecryptedKey());
        if (!$key) {
            $this->addError($attribute, 'Key is not a private key');
            return;
        }

        if (! openssl_x509_check_private_key($this->getDecryptedCertificateObject(), $key)) {
            $this->addError($attribute, 'Key and certificate are not a pair.');
        }
    }

    /**
     * @inheritdoc
     */
    public function beforeSave($insert): bool
    {

        if ($this->isEncrypted && $this->isDecrypted) {
            KeyChain::getInstance()->getService()->encrypt($this);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * Call to fetch key using the getter decrypts
     * @return bool|string
     */
    public function getDecryptedKey()
    {
        if (! $this->decryptedKey) {
            KeyChain::getInstance()->getService()->decrypt($this);
            $this->isDecrypted = true;
        }

        return $this->decryptedKey;
    }

    /**
     * Call to fetch certificate using the getter decrypts
     * @return bool|string
     */
    public function getDecryptedCertificate()
    {
        if (! $this->decryptedCertificate) {
            KeyChain::getInstance()->getService()->decrypt($this);
        }

        return $this->decryptedCertificate;
    }

    /**
     * @return ?\OpenSSLCertificate
     */
    protected function getDecryptedCertificateObject()
    {
        $certificateString = $this->getDecryptedCertificate();
        if (!$certificateString) {
            return null;
        }

        $cert = openssl_x509_read($certificateString);
        if (!$cert) {
            return null;
        }

        return $cert;
    }

    /**
     * If the certificate is parsable, returns the \DateTimeImmutable that it expires, null otherwise.
     * @return ?\DateTimeImmutable
     */
    public function getCertificateExpiration()
    {
        $certText = $this->getDecryptedCertificate();
        $x509Data = openssl_x509_parse($certText);
        if (!$x509Data) {
            return null;
        }
        return new \DateTimeImmutable(sprintf('@%d', $x509Data['validTo_time_t']));
    }
}
